### ISSUE TITLE
[BUG] 오늘날짜 이미지가 다른이미지에 비해 작음

### ISSUE THREAD

**Issue by JMLEE0** [yeolsimee/MoneySaving-Android#51]
홈
오늘날짜 이미지가 다른이미지에 비해 작음
![image](https://github.com/yeolsimee/ROUMO-Android/assets/84388335/2e8f0e55-daff-4ccd-b626-9fb9e0c50e7e)

**Comment by boring-km** [comment]
@JMLEE0 이거 재현이 잘 안되는데 특정 재현 상황이 있을까요..?

![image](https://github.com/yeolsimee/ROUMO-Android/assets/34850203/c8e6ab91-2286-4b60-b40d-f3f008351fed)

**Comment by boring-km** [comment]
이미지 해상도 문제로 확인 -> today 이미지 사이즈 28dp 적용
