### ISSUE TITLE
[FEAT] 카테고리명 수정하기, 카테고리 삭제하기 선택 화면

### ISSUE THREAD

**Issue by Jay0727** [yeolsimee/MoneySaving-Android#77]
## 추가할 기능
카테고리명 수정하기, 삭제하기 선택 화면 추가 

## 적용될 화면 위치
![image](https://github.com/yeolsimee/ROUMO-Android/assets/136715300/b56948a9-b1db-4a0c-864f-7f9e0590058c)
디자인 개발용 피그잼- 최종 쪽 확인 
### 추가 설명
기능 명세서 참조

**Comment by boring-km** [comment]
기능 명세서 링크: [https://1drv.ms/x/s!AgpkhQ9D6MwAjyFEfSRhdaSVlV0E?e=2m1juO](https://1drv.ms/x/s!AgpkhQ9D6MwAjyFEfSRhdaSVlV0E?e=2m1juO)
